// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Describes the text label to put on the Location Button.
enum LocationButtonTextType {
  /// The button won't contain any text.
  none,
  /// The button will have the localized label "Precise location".
  preciseLocation,
  /// The button will have the localized label "Use precise location".
  usePreciseLocation,
  /// The button will have the localized label "Share precise location".
  sharePreciseLocation,
  /// The button will have the localized label "Near my precise location".
  nearMyPreciseLocation,
  /// The button will have the localized label "Near your precise location".
  nearYourPreciseLocation;
}

/// Describes the appearance of the Location Button.
class RawLocationButtonStyle {
  RawLocationButtonStyle({
    required this.height,
    required this.width,
    this.backgroundColor,
    this.iconTintColor,
    this.textColor,
    required this.textType,
    this.strokeColor,
    required this.strokeWidth,
    this.bottomPadding,
    this.leftPadding,
    this.rightPadding,
    this.topPadding,
    this.cornerRadius,
    this.pressedCornerRadius,
  });

  /// The height of the button, between 48dp and 136dp (inclusive).
  int height;

  /// The width of the button, at least 48dp.
  int width;

  /// The ARGB value for the background color. The alpha channel is
  /// automatically overridden to opaque.
  int? backgroundColor;

  /// The ARGB value for the tint of the icon of the button. The minimum
  /// contrast ratio for the tint is 4.5:1. The system may shift the color of
  /// the icon to satisfy this constraint.
  int? iconTintColor;

  /// The ARGB value for the color of the text of the button (if present). The
  /// minimum contrast ratio for the color is 4.5:1. The system may shift the
  /// color of the text to satisfy this constraint.
  int? textColor;

  /// The type of label to display on top of the bottom.
  LocationButtonTextType textType;

  /// The color of the outline around the button. Defaults to the
  /// [backgroundColor].
  int? strokeColor;

  /// The thickness of the outline formed around the button. The value ranges
  /// between 0dp and 3dp (inclusive).
  int strokeWidth;

  /// The bottom padding for the button. Ranges between 4dp and 8dp (inclusive).
  int? bottomPadding;

  /// The left padding for the button. Ranges between 4dp and 8dp (inclusive).
  int? leftPadding;

  /// The right padding for the button. Ranges between 4dp and 8dp (inclusive).
  int? rightPadding;

  /// The top padding for the button. Ranges between 4dp and 8dp (inclusive).
  int? topPadding;

  /// Corner radius for the button when it is unpressed. Must be positive.
  double? cornerRadius;

  /// Corner radius for the button when it is pressed. Must be positive.
  double? pressedCornerRadius;

  List<Object?> _toList() {
    return <Object?>[
      height,
      width,
      backgroundColor,
      iconTintColor,
      textColor,
      textType,
      strokeColor,
      strokeWidth,
      bottomPadding,
      leftPadding,
      rightPadding,
      topPadding,
      cornerRadius,
      pressedCornerRadius,
    ];
  }

  Object encode() {
    return _toList();  }

  static RawLocationButtonStyle decode(Object result) {
    result as List<Object?>;
    return RawLocationButtonStyle(
      height: result[0]! as int,
      width: result[1]! as int,
      backgroundColor: result[2] as int?,
      iconTintColor: result[3] as int?,
      textColor: result[4] as int?,
      textType: result[5]! as LocationButtonTextType,
      strokeColor: result[6] as int?,
      strokeWidth: result[7]! as int,
      bottomPadding: result[8] as int?,
      leftPadding: result[9] as int?,
      rightPadding: result[10] as int?,
      topPadding: result[11] as int?,
      cornerRadius: result[12] as double?,
      pressedCornerRadius: result[13] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RawLocationButtonStyle || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(height, other.height) && _deepEquals(width, other.width) && _deepEquals(backgroundColor, other.backgroundColor) && _deepEquals(iconTintColor, other.iconTintColor) && _deepEquals(textColor, other.textColor) && _deepEquals(textType, other.textType) && _deepEquals(strokeColor, other.strokeColor) && _deepEquals(strokeWidth, other.strokeWidth) && _deepEquals(bottomPadding, other.bottomPadding) && _deepEquals(leftPadding, other.leftPadding) && _deepEquals(rightPadding, other.rightPadding) && _deepEquals(topPadding, other.topPadding) && _deepEquals(cornerRadius, other.cornerRadius) && _deepEquals(pressedCornerRadius, other.pressedCornerRadius);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RawLocationButtonStyle(height: $height, width: $width, backgroundColor: $backgroundColor, iconTintColor: $iconTintColor, textColor: $textColor, textType: $textType, strokeColor: $strokeColor, strokeWidth: $strokeWidth, bottomPadding: $bottomPadding, leftPadding: $leftPadding, rightPadding: $rightPadding, topPadding: $topPadding, cornerRadius: $cornerRadius, pressedCornerRadius: $pressedCornerRadius)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LocationButtonTextType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is RawLocationButtonStyle) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : LocationButtonTextType.values[value];
      case 130:
        return RawLocationButtonStyle.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LocationButtonApi {
  /// Constructor for [LocationButtonApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LocationButtonApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// Creates a Location Button session that starts drawing the button on
  /// screen.
  Future<bool> createSession(int sessionHandle, RawLocationButtonStyle style) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_location_button.LocationButtonApi.createSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionHandle, style]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Updates visually the button to match the [newStyle].
  Future<void> updateButton(int sessionHandle, RawLocationButtonStyle oldStyle, RawLocationButtonStyle newStyle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_location_button.LocationButtonApi.updateButton$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionHandle, oldStyle, newStyle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Closes definitively the session and stops the button from drawing /
  /// working.
  Future<void> closeSession(int sessionHandle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_location_button.LocationButtonApi.closeSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionHandle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Asks the user for the broader location permission, if possible. Returns
  /// true if granted.
  Future<bool> requestPermission(int sessionHandle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_location_button.LocationButtonApi.requestPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionHandle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Asks for the button text localizations explicitly (we use this so that we
  /// can fetch them when we hot restart...)
  Future<Map<LocationButtonTextType, String>> fetchLocalization() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_location_button.LocationButtonApi.fetchLocalization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<LocationButtonTextType, String>();
  }
}

abstract class LocationButtonCallback {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when the user pressed the Location Button and picked whether to
  /// temporarily grant the precise location permission.
  void permissionResult(int sessionHandle, bool granted);

  /// Called when the session prematurely dies, for whatever reason.
  void sessionDead(int sessionHandle);

  /// Called when the language for the app changes.
  void newLocalizations(Map<LocationButtonTextType, String> newLocalizations);

  static void setUp(LocationButtonCallback? api, {
    BinaryMessenger? binaryMessenger, 
    String messageChannelSuffix = '',
  }) 
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_location_button.LocationButtonCallback.permissionResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_sessionHandle = args[0]! as int;
          final bool arg_granted = args[1]! as bool;
          try {
            api.permissionResult(arg_sessionHandle, arg_granted);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_location_button.LocationButtonCallback.sessionDead$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_sessionHandle = args[0]! as int;
          try {
            api.sessionDead(arg_sessionHandle);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_location_button.LocationButtonCallback.newLocalizations$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final Map<LocationButtonTextType, String> arg_newLocalizations = (args[0]! as Map<Object?, Object?>).cast<LocationButtonTextType, String>();
          try {
            api.newLocalizations(arg_newLocalizations);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
