// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package fr.antinote.flutter_location_button

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object GeneratedFlutterLocationButtonApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Describes the text label to put on the Location Button. */
enum class LocationButtonTextType(val raw: Int) {
  /** The button won't contain any text. */
  NONE(0),
  /** The button will have the localized label "Precise location". */
  PRECISE_LOCATION(1),
  /** The button will have the localized label "Use precise location". */
  USE_PRECISE_LOCATION(2),
  /** The button will have the localized label "Share precise location". */
  SHARE_PRECISE_LOCATION(3),
  /** The button will have the localized label "Near my precise location". */
  NEAR_MY_PRECISE_LOCATION(4),
  /** The button will have the localized label "Near your precise location". */
  NEAR_YOUR_PRECISE_LOCATION(5);

  companion object {
    fun ofRaw(raw: Int): LocationButtonTextType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Describes the appearance of the Location Button.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RawLocationButtonStyle (
  /** The height of the button, between 48dp and 136dp (inclusive). */
  val height: Long,
  /** The width of the button, at least 48dp. */
  val width: Long,
  /**
   * The ARGB value for the background color. The alpha channel is
   * automatically overridden to opaque.
   */
  val backgroundColor: Long? = null,
  /**
   * The ARGB value for the tint of the icon of the button. The minimum
   * contrast ratio for the tint is 4.5:1. The system may shift the color of
   * the icon to satisfy this constraint.
   */
  val iconTintColor: Long? = null,
  /**
   * The ARGB value for the color of the text of the button (if present). The
   * minimum contrast ratio for the color is 4.5:1. The system may shift the
   * color of the text to satisfy this constraint.
   */
  val textColor: Long? = null,
  /** The type of label to display on top of the bottom. */
  val textType: LocationButtonTextType,
  /**
   * The color of the outline around the button. Defaults to the
   * [backgroundColor].
   */
  val strokeColor: Long? = null,
  /**
   * The thickness of the outline formed around the button. The value ranges
   * between 0dp and 3dp (inclusive).
   */
  val strokeWidth: Long,
  /** The bottom padding for the button. Ranges between 4dp and 8dp (inclusive). */
  val bottomPadding: Long? = null,
  /** The left padding for the button. Ranges between 4dp and 8dp (inclusive). */
  val leftPadding: Long? = null,
  /** The right padding for the button. Ranges between 4dp and 8dp (inclusive). */
  val rightPadding: Long? = null,
  /** The top padding for the button. Ranges between 4dp and 8dp (inclusive). */
  val topPadding: Long? = null,
  /** Corner radius for the button when it is unpressed. Must be positive. */
  val cornerRadius: Double? = null,
  /** Corner radius for the button when it is pressed. Must be positive. */
  val pressedCornerRadius: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RawLocationButtonStyle {
      val height = pigeonVar_list[0] as Long
      val width = pigeonVar_list[1] as Long
      val backgroundColor = pigeonVar_list[2] as Long?
      val iconTintColor = pigeonVar_list[3] as Long?
      val textColor = pigeonVar_list[4] as Long?
      val textType = pigeonVar_list[5] as LocationButtonTextType
      val strokeColor = pigeonVar_list[6] as Long?
      val strokeWidth = pigeonVar_list[7] as Long
      val bottomPadding = pigeonVar_list[8] as Long?
      val leftPadding = pigeonVar_list[9] as Long?
      val rightPadding = pigeonVar_list[10] as Long?
      val topPadding = pigeonVar_list[11] as Long?
      val cornerRadius = pigeonVar_list[12] as Double?
      val pressedCornerRadius = pigeonVar_list[13] as Double?
      return RawLocationButtonStyle(height, width, backgroundColor, iconTintColor, textColor, textType, strokeColor, strokeWidth, bottomPadding, leftPadding, rightPadding, topPadding, cornerRadius, pressedCornerRadius)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      height,
      width,
      backgroundColor,
      iconTintColor,
      textColor,
      textType,
      strokeColor,
      strokeWidth,
      bottomPadding,
      leftPadding,
      rightPadding,
      topPadding,
      cornerRadius,
      pressedCornerRadius,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RawLocationButtonStyle
    return GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.height, other.height) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.width, other.width) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.backgroundColor, other.backgroundColor) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.iconTintColor, other.iconTintColor) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.textColor, other.textColor) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.textType, other.textType) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.strokeColor, other.strokeColor) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.strokeWidth, other.strokeWidth) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.bottomPadding, other.bottomPadding) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.leftPadding, other.leftPadding) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.rightPadding, other.rightPadding) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.topPadding, other.topPadding) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.cornerRadius, other.cornerRadius) && GeneratedFlutterLocationButtonApiPigeonUtils.deepEquals(this.pressedCornerRadius, other.pressedCornerRadius)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.height)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.width)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.backgroundColor)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.iconTintColor)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.textColor)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.textType)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.strokeColor)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.strokeWidth)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.bottomPadding)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.leftPadding)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.rightPadding)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.topPadding)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.cornerRadius)
    result = 31 * result + GeneratedFlutterLocationButtonApiPigeonUtils.deepHash(this.pressedCornerRadius)
    return result
  }
  override fun toString(): String {
    return "RawLocationButtonStyle(height=$height, width=$width, backgroundColor=$backgroundColor, iconTintColor=$iconTintColor, textColor=$textColor, textType=$textType, strokeColor=$strokeColor, strokeWidth=$strokeWidth, bottomPadding=$bottomPadding, leftPadding=$leftPadding, rightPadding=$rightPadding, topPadding=$topPadding, cornerRadius=$cornerRadius, pressedCornerRadius=$pressedCornerRadius)"
  }
}
private open class GeneratedFlutterLocationButtonApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LocationButtonTextType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RawLocationButtonStyle.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LocationButtonTextType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is RawLocationButtonStyle -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LocationButtonApi {
  /**
   * Creates a Location Button session that starts drawing the button on
   * screen.
   */
  suspend fun createSession(sessionHandle: Long, style: RawLocationButtonStyle): Boolean
  /** Updates visually the button to match the [newStyle]. */
  fun updateButton(sessionHandle: Long, oldStyle: RawLocationButtonStyle, newStyle: RawLocationButtonStyle)
  /**
   * Closes definitively the session and stops the button from drawing /
   * working.
   */
  fun closeSession(sessionHandle: Long)
  /**
   * Asks the user for the broader location permission, if possible. Returns
   * true if granted.
   */
  fun requestPermission(sessionHandle: Long, callback: (Result<Boolean>) -> Unit)
  /**
   * Asks for the button text localizations explicitly (we use this so that we
   * can fetch them when we hot restart...)
   */
  fun fetchLocalization(): Map<LocationButtonTextType, String>

  companion object {
    /** The codec used by LocationButtonApi. */
    val codec: MessageCodec<Any?> by lazy {
      GeneratedFlutterLocationButtonApiPigeonCodec()
    }
    /** Sets up an instance of `LocationButtonApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LocationButtonApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_location_button.LocationButtonApi.createSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as Long
            val styleArg = args[1] as RawLocationButtonStyle
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createSession(sessionHandleArg, styleArg))
              } catch (exception: Throwable) {
                GeneratedFlutterLocationButtonApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_location_button.LocationButtonApi.updateButton$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as Long
            val oldStyleArg = args[1] as RawLocationButtonStyle
            val newStyleArg = args[2] as RawLocationButtonStyle
            val wrapped: List<Any?> = try {
              api.updateButton(sessionHandleArg, oldStyleArg, newStyleArg)
              listOf(null)
            } catch (exception: Throwable) {
              GeneratedFlutterLocationButtonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_location_button.LocationButtonApi.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.closeSession(sessionHandleArg)
              listOf(null)
            } catch (exception: Throwable) {
              GeneratedFlutterLocationButtonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_location_button.LocationButtonApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionHandleArg = args[0] as Long
            api.requestPermission(sessionHandleArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GeneratedFlutterLocationButtonApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(GeneratedFlutterLocationButtonApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_location_button.LocationButtonApi.fetchLocalization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.fetchLocalization())
            } catch (exception: Throwable) {
              GeneratedFlutterLocationButtonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LocationButtonCallback(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LocationButtonCallback. */
    val codec: MessageCodec<Any?> by lazy {
      GeneratedFlutterLocationButtonApiPigeonCodec()
    }
  }
  /**
   * Called when the user pressed the Location Button and picked whether to
   * temporarily grant the precise location permission.
   */
  suspend fun permissionResult(sessionHandleArg: Long, grantedArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_location_button.LocationButtonCallback.permissionResult$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(sessionHandleArg, grantedArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(GeneratedFlutterLocationButtonApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /** Called when the session prematurely dies, for whatever reason. */
  suspend fun sessionDead(sessionHandleArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_location_button.LocationButtonCallback.sessionDead$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(sessionHandleArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(GeneratedFlutterLocationButtonApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /** Called when the language for the app changes. */
  suspend fun newLocalizations(newLocalizationsArg: Map<LocationButtonTextType, String>)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.flutter_location_button.LocationButtonCallback.newLocalizations$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(newLocalizationsArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(GeneratedFlutterLocationButtonApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
